plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
