name: "Codecov"

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/codecov.yml'
      - 'hevc-portainer/**'
      - 'hevc-processor/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Generate hevc-portainer coverage report
        working-directory: hevc-portainer
        run: |
          pip install poetry
          poetry install
          poetry build
          poetry run pytest --cov=./ --cov-report=xml
      - name: Generate hevc-processor coverage report
        working-directory: hevc-processor
        run: |
          pip install poetry
          poetry install
          poetry build
          poetry run pytest --cov=./ --cov-report=xml
      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: python-coverage
          path: |
            hevc-portainer/coverage.xml
            hevc-processor/coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: hevc-portainer/coverage.xml,hevc-processor/coverage.xml
          flags: unittests
          verbose: true
