name: "Docker / portainer-api-client"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/docker-portainer-api-client.yml'
      - 'docker/portainer-api-client/**'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag variable for docker
        shell: bash
        run: |
          BRANCH="$(echo ${GITHUB_REF#refs/heads/})"
          if [[ "$BRANCH" == "main" ]]; then
            echo "DOCKER_TAG=melvyndekort/portainer-api-client:latest" >> "$GITHUB_ENV"
          else
            echo "DOCKER_TAG=melvyndekort/portainer-api-client:$BRANCH" >> "$GITHUB_ENV"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/portainer-api-client
          push: true
          tags: ${{ env.DOCKER_TAG }}
